title: Yibo Wang's Personal Page
title-research: Research - Yibo Wang
title-contact: Contact - Yibo Wang
page-top-title: Yibo Wang
top-section-bg-text: Electrical and Computer Engineering
home-subtitle: Yibo Wang&ensp;|&ensp;王艺博
copyright-text: '&copy; Yibo Wang 2026-2027. All Rights Reserved.'
